apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice-1.fullname" . }}
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
    {{- if .Values.backendConfig.enabled }}
    cloud.google.com/backend-config: '{"ports": {"http":"{{ include "microservice-1.fullname" . }}-backendconfig"}}'
    {{- end }}
  labels:
    {{- include "microservice-1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}

      targetPort: http # This should match the name of the port in your deployment's container spec
      protocol: {{ .Values.service.protocol }}
      name: http
  selector:
    {{- include "microservice-1.selectorLabels" . | nindent 4 }}