apiVersion: v2
name: microservice-2
description: DogfyDiet Microservice 2 - Subscriber and Data Processor
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/your-username/dogfydiet-platform
sources:
  - https://github.com/your-username/dogfydiet-platform
maintainers:
  - name: DogfyDiet Platform Team
    email: nahuel@gavilanbe.io
keywords:
  - microservice
  - subscriber
  - firestore
  - pubsub
  - dogfydiet
annotations:
  category: Application